# .github/workflows/ci.yml

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pip-tools
          pip-compile requirements.in -o requirements.txt
          pip install -r requirements.txt
      
      
      - name: Configure DVC with MinIO
        env:
          # این مقادیر را از Secrets گیت‌هاب می‌خوانیم
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
        run: |
          dvc remote modify myremote endpointurl $MINIO_ENDPOINT_URL
          dvc remote modify myremote access_key_id $MINIO_ACCESS_KEY
          dvc remote modify myremote secret_access_key $MINIO_SECRET_KEY

      - name: Pull DVC data
        run: |
          dvc pull -v

      - name: Reproduce DVC pipeline
        run: |
          dvc repro -v